# SConscript
# Copyright 2011 Philipp Stephani
#
# This work may be distributed and/or modified under the
# conditions of the LaTeX Project Public License, either version 1.3c
# of this license or (at your option) any later version.
# The latest version of this license is in
#   http://www.latex-project.org/lppl.txt
# and version 1.3c or later is part of all distributions of LaTeX
# version 2009/09/24 or later.
#
# This work has the LPPL maintenance status `maintained'.
# The Current Maintainer of this work is Philipp Stephani.
# This work consists of all files listed in MANIFEST.

import subprocess

import utilities

freetype_cflags = utilities.check_output("freetype-config", "--cflags").rstrip()
freetype_libs = utilities.check_output("freetype-config", "--libs").rstrip()
env = Environment(CCFLAGS="-Wall -Wextra -Werror " + freetype_cflags, LINKFLAGS=freetype_libs)
env.Program("ftparams", "main.cpp")
